### Chat
POST http://localhost:3000/chat
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Tell me a joke"
                }
            ]
        }
    ],
    "temperature": 1,
    "max_tokens": 1000
}

### Chat Stream
POST http://localhost:3000/chat/stream
Content-Type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Tell me a joke"
                }
            ]
        }
    ],
    "temperature": 1,
    "max_tokens": 1000
}